kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "Django API"
paths = ["/api", "/media"]

[services.development]
run = "python /home/runner/workspace/backend/manage.py runserver 0.0.0.0:8000 --noreload"
