# Generated by Django 5.2.15 on 2026-06-28 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels_app', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels_app.publishchannel')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_jobs', to='content.content')),
            ],
            options={
                'db_table': 'publishing_publishjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField()),
                ('success', models.BooleanField()),
                ('error_type', models.CharField(blank=True, choices=[('connection_error', 'Connection Error'), ('auth_error', 'Auth Error'), ('bot_removed', 'Bot Removed'), ('rate_limit', 'Rate Limit'), ('unknown', 'Unknown')], max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('user_message', models.TextField(blank=True)),
                ('api_response', models.JSONField(null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='publishing.publishjob')),
            ],
            options={
                'db_table': 'publishing_publishlog',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
