# Generated by Django 5.2.15 on 2026-07-04 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('publishing', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishlog',
            name='error_type',
            field=models.CharField(blank=True, choices=[('connection_error', 'Connection Error'), ('auth_error', 'Auth Error'), ('bot_removed', 'Bot Removed'), ('rate_limit', 'Rate Limit'), ('unsupported_media', 'Unsupported Media'), ('unknown', 'Unknown')], max_length=30),
        ),
        migrations.CreateModel(
            name='PublishAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('voice', 'Voice'), ('document', 'Document')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.content')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_attachments', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'publishing_publishattachment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='publishjob',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='publish_jobs', to='publishing.publishattachment'),
        ),
    ]
