# Generated by Django 5.2.15 on 2026-06-28 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale')], max_length=20)),
                ('token', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channels_channelverification',
            },
        ),
        migrations.CreateModel(
            name='PublishChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale'), ('website', 'Website')], max_length=20)),
                ('channel_type', models.CharField(blank=True, choices=[('channel', 'Channel'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('page', 'Page')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channels_publishchannel',
            },
        ),
    ]
