# Generated by Django 5.2.15 on 2026-07-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelverification',
            name='channel_type',
            field=models.CharField(choices=[('channel', 'Channel'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('page', 'Page')], default='channel', max_length=20),
        ),
        migrations.AddField(
            model_name='channelverification',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
