# Generated by Django 5.2.15 on 2026-07-04 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0003_channelverification_channel_type_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelverification',
            name='channel_type',
            field=models.CharField(choices=[('channel', 'Channel'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('page', 'Page'), ('personal', 'Personal Profile'), ('organization', 'Company Page'), ('site', 'Website')], default='channel', max_length=20),
        ),
        migrations.AlterField(
            model_name='publishchannel',
            name='channel_type',
            field=models.CharField(blank=True, choices=[('channel', 'Channel'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('page', 'Page'), ('personal', 'Personal Profile'), ('organization', 'Company Page'), ('site', 'Website')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publishchannel',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale'), ('website', 'Website'), ('linkedin', 'LinkedIn'), ('wordpress', 'WordPress')], max_length=20),
        ),
        migrations.CreateModel(
            name='LinkedInConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_target', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], default='personal', max_length=20)),
                ('person_urn', models.CharField(blank=True, max_length=255)),
                ('organization_urn', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_reauth', 'Needs Reauth'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_connections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_connections', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'channels_linkedinconnection',
            },
        ),
        migrations.CreateModel(
            name='WordPressConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_url', models.URLField(max_length=500)),
                ('wp_username', models.CharField(max_length=255)),
                ('application_password', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('invalid', 'Invalid'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordpress_connections', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordpress_connections', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'channels_wordpressconnection',
                'unique_together': {('workspace', 'site_url')},
            },
        ),
    ]
