# Generated by Django 5.2 on 2026-07-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('channels_app', '0004_alter_channelverification_channel_type_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinconnection', name='avatar_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='linkedinconnection', name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinconnection', name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='linkedinconnection', name='linkedin_subject_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkedinconnection', name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='linkedinconnection', name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='linkedinconnection', name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='linkedinconnection',
            constraint=models.UniqueConstraint(
                fields=('workspace', 'platform_target'),
                name='unique_linkedin_target_per_workspace',
            ),
        ),
        migrations.AddIndex(
            model_name='linkedinconnection',
            index=models.Index(fields=['workspace', 'status', 'is_active'], name='linkedin_conn_status_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinconnection',
            index=models.Index(fields=['linkedin_subject_id'], name='linkedin_subject_idx'),
        ),
        migrations.CreateModel(
            name='LinkedInOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('platform_target', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], default='personal', max_length=20)),
                ('frontend_origin', models.URLField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_oauth_states', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'channels_linkedinoauthstate',
                'indexes': [models.Index(fields=['expires_at', 'consumed_at'], name='linkedin_oauth_exp_idx')],
            },
        ),
    ]
