# Generated by Django 6.0.7 on 2026-07-14 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('provider_key', models.CharField(choices=[('kavenegar', 'Kavenegar'), ('gmail_smtp', 'Gmail SMTP'), ('custom_smtp', 'Custom SMTP')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(choices=[('not_tested', 'Not Tested'), ('connected', 'Connected'), ('failed', 'Failed')], default='not_tested', max_length=20)),
                ('last_test_error', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'communication_provider',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('body_type', models.CharField(choices=[('plain_text', 'Plain text'), ('html', 'HTML')], default='plain_text', max_length=20)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('valid_recipients_count', models.PositiveIntegerField(default=0)),
                ('invalid_recipients_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='communication.communicationprovider')),
            ],
            options={
                'db_table': 'communication_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'communication_contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('rendered_subject', models.CharField(blank=True, max_length=500)),
                ('rendered_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('is_test', models.BooleanField(default=False)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.contact')),
            ],
            options={
                'db_table': 'communication_campaign_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='selected_contacts',
            field=models.ManyToManyField(blank=True, related_name='selected_campaigns', to='communication.contact'),
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'communication_contact_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='selected_groups',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='communication.contactgroup'),
        ),
        migrations.CreateModel(
            name='ContactGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='communication.contact')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communication.contactgroup')),
            ],
            options={
                'db_table': 'communication_contact_group_member',
            },
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(related_name='groups', through='communication.ContactGroupMember', to='communication.contact'),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='communication/imports/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('completed', 'Completed'), ('failed', 'Failed')], default='previewed', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('preview', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'communication_import_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('body_type', models.CharField(choices=[('plain_text', 'Plain text'), ('html', 'HTML')], default='plain_text', max_length=20)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'communication_message_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.messagetemplate'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'status'], name='comm_contact_ws_status'),
        ),
        migrations.AddIndex(
            model_name='campaignmessage',
            index=models.Index(fields=['campaign', 'status'], name='comm_message_campaign_status'),
        ),
        migrations.AddConstraint(
            model_name='contactgroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'contact'), name='unique_comm_group_member'),
        ),
        migrations.AddConstraint(
            model_name='contactgroup',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_comm_group_name'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['workspace', 'status'], name='comm_campaign_ws_status'),
        ),
    ]
