# Generated by Django 5.2.15 on 2026-07-01 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('standard', 'استاندارد'), ('bundle', 'بازتولید همزمان'), ('multi_variant', 'چندگزینه\u200cای')], max_length=20)),
                ('capability', models.CharField(max_length=30)),
                ('topic', models.TextField()),
                ('tone', models.CharField(blank=True, max_length=30)),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('variant_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wallet_cost_charged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_batches', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_engine_generationbatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('full_text', 'متن کامل'), ('short_text', 'نسخه کوتاه'), ('hashtags', 'هشتگ\u200cها'), ('title', 'عنوان'), ('variant', 'نسخه')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField()),
                ('saved_as_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_engine.generationbatch')),
            ],
            options={
                'db_table': 'ai_engine_generateditem',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
