# Generated by Django 5.2.15 on 2026-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_generationbatch_generateditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/'),
        ),
        migrations.AddField(
            model_name='generationbatch',
            name='image_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='generateditem',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generateditem',
            name='item_type',
            field=models.CharField(choices=[('full_text', 'متن کامل'), ('short_text', 'نسخه کوتاه'), ('hashtags', 'هشتگ\u200cها'), ('title', 'عنوان'), ('variant', 'نسخه'), ('image', 'تصویر')], max_length=20),
        ),
    ]
